apiVersion: 1
groups:
    - orgId: 1
      name: fastapisample
      folder: fastapisample
      interval: 5m
      rules:
        - uid: ceulsvy8vlc74d
          title: fasapisample_up
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: builder
                expr: up{job="fastapisample"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          annotations:
            description: d=fastapi down
            summary: fastapi down
          labels:
            fastapisample: "1"
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
